# Generated by Django 5.1 on 2024-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='branches',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
