# Generated by Django 5.1 on 2024-09-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_branches_email_alter_branches_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentsBranche', to='company.branches'),
        ),
    ]
