# Generated by Django 5.1 on 2024-09-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_departments_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
