# Generated by Django 5.1 on 2024-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_branches_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='description',
            field=models.TextField(help_text='write description about the department', max_length=200),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
