# Generated by Django 5.1 on 2024-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_departments_description_alter_departments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='departments',
            unique_together={('name', 'branch')},
        ),
    ]
